### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jnalanko** [baharpan/dynboss#4]
Hi,

Dynboss is segfaulting on me. I built the program with the commands in the readme and then ran the following commands:

```
dsk-1.6906/dsk data/0.fasta 30
bin/cosmo-pack 0.solid_kmers_binary
bin/dynamicBOSS build -p 0.solid_kmers_binary.packed
bin/dynamicBOSS add -g 0.solid_kmers_binary.packed.dbg -s data/1.fasta
```

My data is attached. This crashes with a segmentation fault after processing 1.71112% of the k-mers. The gdb debugger gives the following backtrace:

```
#0  0x00005555555673d0 in dyn::wt_string<dyn::succinct_bitvector<dyn::spsi<dyn::packed_bit_vector, 8192u, 16u> > >::select(unsigned long, unsigned long) const ()
#1  0x0000555555567a4d in dyn_boss::index_edge_alan(__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, unsigned long&) ()
#2  0x000055555555ac1c in main ()
```

[data.zip](https://github.com/baharpan/dynboss/files/5823857/data.zip)

**Comment by jnalanko** [comment]
I think I found the issue. The input file 1.fna had 'N'-characters and other non-ACGT-characters even though the readme says there should not have those. Sorry, my bad. A more graceful failure could be nice though.
